### ISSUE TITLE
Getting hugging face error in my local docker 

### ISSUE THREAD

**Issue by ghousethanedar** [facebookresearch/llm-transparency-tool#18]
Hi 

I am trying to use the application via docker.
steps i have tried 

first i have cloned the repo and then 

Created the docker image using the commands provided 
docker build -t llm_transparency_tool .
and it got created successfully.

![image](https://github.com/facebookresearch/llm-transparency-tool/assets/37260980/38fec524-b805-4de1-a3fe-525be7129c7d)

and i have ran the docker image using below command.

docker run --rm -p 7860:7860 llm_transparency_tool

after this i am getting below error 

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like gpt2 is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

![image](https://github.com/facebookresearch/llm-transparency-tool/assets/37260980/71f1f758-6e64-4b74-8cd0-0f29ca1d9d65)

could you please help me to solve this.

Appreciate the wonderful effort.

Regards,
Basha

**Comment by mahnerak** [comment]
Hey @ghousethanedar 
Thanks for the interest in our work!

I noticed couple of hours ago some connectivity issues with huggingface hub too.
But it [seems to be resolved now](https://status.huggingface.co/).

Can you please retry it one more time?

**Comment by ghousethanedar** [comment]
Thanks @mahnerak 
Great work 
Now it is working yesterday hugging face hub was down for sometime
