### ISSUE TITLE
llama-2-70B support

### ISSUE THREAD

**Issue by tsaoyu** [facebookresearch/llm-transparency-tool#20]
Thanks for the project. 

Since the `TransformerLens` project now support GQA, I installed the latest version from their git for Llama-2 70B support.
However, `llm-transparency-tool` complains the following 

```
RuntimeError: The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 1
```

from https://github.com/facebookresearch/llm-transparency-tool/blob/main/llm_transparency_tool/models/tlens_model.py#L287

Does that something related to Llama2's GQA?

**Comment by mahnerak** [comment]
Now LLama-2 70B and all LLama-3 models are supported.
