### ISSUE TITLE
unable to disable telemetry in streamlit

### ISSUE THREAD

**Issue by poedator** [facebookresearch/llm-transparency-tool#34]
I am trying to disable spying and change port by entering command line argument, but they get ignored:
```
streamlit run llm_transparency_tool/server/app.py -- config/local.json --server.port 6504 --browser.gatherUsageStats false

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.2:8501
  External URL: http://141.8.129.105:8501

```
please update the config and instructions

**Comment by mahnerak** [comment]
This is usage statistics collected by Streamlit (third party, not affiliated with Meta).
**We do not collect ANY data**.

---

The correct way is:
```
streamlit run  --server.port 6504 --browser.gatherUsageStats false llm_transparency_tool/server/app.py -- config/local.json
```

Basically, whatever arguments are passed after ` -- ` is accessed by our script. Arguments before that is handled by streamlit. Both `--server.port 6504` and `--browser.gatherUsageStats false` are **streamlit flags, so should come before ` -- `**.


There's also way of defining system-wide / project-wide configs for streamlit here: https://docs.streamlit.io/develop/api-reference/configuration/config.toml

**Comment by poedator** [comment]
thank you, this solves the issue

**Comment by poedator** [comment]
thank you, this solves the issue
